# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: required
r_binary_packages:
  - dismo
  - dplyr
  - gbm
  - kernlab
  - magrittr
  - maptools
  - mlr
  - randomForest
  - raster
  - rgbif
  - rgdal
  - rpart
  - shiny
  - shinydashboard
  - shinyjs
  - tidyr
  - xgboost
cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
